# Generated by Django 4.2.3 on 2023-09-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='sender',
        ),
    ]
