# Generated by Django 4.2.3 on 2023-09-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_post_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/02.jpg', upload_to='blog/'),
        ),
    ]
